### ISSUE TITLE
Change Redis Location to Test Namespace

### ISSUE THREAD

**Issue by halspang** [dapr/test-infra#111]
## Describe the proposal
The updated auth standards for Redis mean that using no password is no longer acceptable. When Redis is deployed, it creates a secret which can then be referenced to access it. In order to do this, we need to change the deployment namespace of Redis from `dapr-components` to `longhaul-test`. Alternatively, we can add part of our deployment script to copy the credential to the correct namespace.

```
dapr-redis-master.dapr-components.svc.cluster.local:6379 -> dapr-redis-master.longhaul-test.svc.cluster.local:6379
```

**Comment by halspang** [comment]
Any PR addressing this should also move from the blank password redis component to using a secret key ref.

```yaml
  - name: redisPassword
    secretKeyRef:
      name: dapr-redis
      key: redis-password
```
